E-commerce/Controllers/CheckoutControllerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_commerce.Models;
using Rotativa;
using ReportViewerForMvc;
using System.Web.Mvc.Html;
/**
* Authors: Rutvik Patel, Ritesh Patel, Himanshu Patel and  Parvati Patel
* Name: CheckoutControllerController.cs
* Description: This file mainly controls the checkout activity of the user it add the item to cart, remove from cart and finally gives option for checkout.
*/
namespace E_commerce.Controllers
{
    [Authorize]
    public class CheckoutControllerController : Controller
    {
        EcommerceModel storeDB = new EcommerceModel();
        const string PromoCode = "FREE";// the checkout is only successful if we enter free in promo code
        
        //
         // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewBag.Total = cart.GetTotal();
            return View();
        }

        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);
            values["PromoCode"] = "Free";
            try
            {
                if (string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.Username = User.Identity.Name;
                    order.OrderDate = DateTime.Now;

                    //Save Order
                    storeDB.Orders.Add(order);
                    storeDB.SaveChanges();
                    //Process the order
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete",
                        new { id = order.OrderId });
                }
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }

        //
        // GET: /Checkout/Complete
        [AllowAnonymous]
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = storeDB.Orders.Any(
                o => o.OrderId == id );
            OrderDetail Details = storeDB.OrderDetails.Find(id);
            
            Order Detail = storeDB.Orders.Include("OrderDetails").Single(o => o.OrderId == id);
            if (isValid)
            {
                return View(Detail);
            }
            else
            {
                return View("Error");
            }
        }
        [ChildActionOnly]
        public ActionResult CompleteCheckout(int id)
        {
            // Validate customer owns this order
            bool isValid = storeDB.Orders.Any(
                o => o.OrderId == id);
            OrderDetail Details = storeDB.OrderDetails.Find(id);
            Order Detail = storeDB.Orders.Include("OrderDetails").Single(o => o.OrderId == id);
            if (isValid)
            {
                return PartialView(Detail);
            }
            else
            {
                return View("Error");
            }
        }
        public Order CompletevCheckout(int id=9)
        {
            // Validate customer owns this order
            bool isValid = storeDB.Orders.Any(
                o => o.OrderId == id);
            OrderDetail Details = storeDB.OrderDetails.Find(id);
            Order Detail = storeDB.Orders.Include("OrderDetails").Single(o => o.OrderId == id);
          
                return Detail;
          
        }
        public ActionResult ExportToPDF(int id)
        {

            return new Rotativa.ActionAsPdf("Complete",new { id = id})
            {
                FileName = Server.MapPath("~/Content/Invoice.pdf")
            };
        }

        public ActionResult OrderList()
        {
            List<Order> ordelist = storeDB.Orders.Where(o => o.Username == User.Identity.Name).ToList();

            return View(ordelist);
        }

    }

}

E-commerce/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_commerce.Models;
using E_commerce.ViewModels;
/**
 * Authors: Rutvik Patel, Ritesh Patel, Himanshu Patel and  Parvati Patel
 * Name: ShoppingCartController.cs
 * Description: This file mainly to maintain cart in our website.
 */
namespace E_commerce.Controllers
{
    public class ShoppingCartController : Controller
    {
        EcommerceModel storeDB = new EcommerceModel();

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedItem = storeDB.Items
                .Single(item => item.IID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string itemName = storeDB.Carts
                .Single(item => item.RecordId == id).Item.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            ViewBag.Total = cart.GetTotal();
            return Json(results);

        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            ViewData["CartTotal"] = cart.GetTotal();
            
            return PartialView("CartSummary");
        }
    }
}

E-commerce/Views/CheckoutController/AddressAndPayment.cshtml
@model E_commerce.Models.Order

@{
    ViewBag.Title = "Payment Info";
}

<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Address And Payment</h2>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End Page title area -->


<div class="col-md-offset-2 col-md-8">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <fieldset class="scheduler-border">
            <legend class="scheduler-border">Order Info</legend>
            <section id="loginForm">
                <div class="form-horizontal">
                    <h4>Order Info</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.OrderId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @Value = User.Identity.Name, @readonly = "readonly" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">

                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">

                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
               @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Total,  new { htmlAttributes = new { @class = "form-control", @Value= ViewBag.Total, @readonly = "readonly" } })
                </div>
                <div class="col-md-5">
                    @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })

                </div>
            </div>
               

                    <div class="form-group">
                        @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now, @readonly = "readonly" } })
                        </div>
                        <div class="col-md-5">
                            @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <fieldset>
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-offset-1" style="visibility:hidden" >
                                    @Html.Label("Promo Code", htmlAttributes: new { @class = "control-label col-md-2",})
                                    @Html.TextBox("Promo Code", "Free")
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <div class="form-group">
                        <div class="col-md-offset-1 col-md-10">
                            <a href="@Url.Action("Index","ShoppingCart")" class="btn button2">Back To Cart</a>
                            <input type="submit" value="Save" class="btn button3" />
                        </div>
                    </div>
                </div>

            </section>
        </fieldset>

    }
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

E-commerce/Views/CheckoutController/Complete.cshtml
@model E_commerce.Models.Order
@{
    ViewBag.Title = "Order Confirmed";
}
<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Checkout Complete</h2>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End Page title area -->
<div class="col-md-offset-2 col-md-8">
    <br/>

    <fieldset class="scheduler-border">
        <legend class="scheduler-border">Invoice Detail</legend>
        @{Html.RenderAction("CompleteCheckout", "CheckoutController", new { id = Model.OrderId });}
        </fieldset>
    </div>

E-commerce/Views/CheckoutController/CompleteCheckout.cshtml
@model E_commerce.Models.Order
<section id="loginForm">
    <div class="col-md-10">
        <h1>Ecommerce</h1>
    </div>
    <div class="col-md-2">
        <h1>Invoice</h1>
    </div>
    <hr />
    <div>
        <h3> Your Shipping Details</h3>
        <div class="col-md-2">
            <p>Name:</p>
            <p>Address:</p>
            <p>City:</p>
            <p>Email:</p>
        </div>
        <div class="col-md-4">
            <p>@Model.FirstName @Model.LastName</p>
            <p>@Model.Address</p>
            <p>@Model.City</p>
            <p>@Model.Email</p>
        </div>
        <div class="col-md-2">
            <p>Invoice Number:</p>
            <p>Order Date:</p>
            <p>Total Amount:</p>
            <p>Phone Number:</p>
        </div>
        <div class="col-md-4">
            <p>@Model.OrderId</p>
            <p>@Model.OrderDate</p>
            <p>@Model.Total</p>
            <p>@Model.Phone</p>
        </div>
    </div>
    <table cellspacing="0" class="shop_table cart">
        <thead>
            <tr>
                <th class="product-name">Product</th>
                <th class="product-price">Product Image</th>
                <th class="product-price">Unit</th>
                <th class="product-quantity">Quantity</th>
                <th class="product-subtotal">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderDetails)
            {
                <tr>
                    <td class="product-name">
                        @item.Item.Name
                    </td>
                    <td class="product-thumbnail">
                        <a href="single-product.html"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="~/Assests/Uploads/Items/Thumbnails/@item.Item.ThumbUrl"></a>
                    </td>
                    <td class="product-price">
                        @item.UnitPrice
                    </td>
                    <td class="product-price">
                        <span class="amount">@item.Quantity</span>
                    </td>
                    <td class="product-price">
                        <span class="amount">@(item.UnitPrice*item.Quantity)</span>
                    </td>
                   

                </tr>
            }
        </tbody>
    </table>

    <p align="center">Thank for choosing Ecommerce for your shopping.</p>
</section>

E-commerce/Views/CheckoutController/OrderList.cshtml
@model IEnumerable<E_commerce.Models.Order>

@{
    ViewBag.Title = "OrderList";
}



<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Order History</h2>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End Page title area -->
<div class="col-md-offset-1 col-md-10">
    <br/>
    <table class="table table-hover">
        <thead class="tthead">
            <tr>
                <th>
                    Innvoice No
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>Action</th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Total)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Complete", "CheckoutController", new { id = item.OrderId }, new { @class = "btn button3" })
                    </td>
                </tr>
            }

</table>
    </div>